### ISSUE TITLE
Crew pictures in crew selection are distorted 

### ISSUE THREAD

**Issue by mnalis** [nukebloodaxe/Ironseed-py#2]
Comparing to original game, the crew pictures during `crewgen` stage (starting new game and selecting personnel) are elongated by height. Actually, whole screen is elongated (relatively easily seen also by deformed `accept`/`reject` buttons.
Python:
![crew-py](https://user-images.githubusercontent.com/156656/93512993-74636a80-f925-11ea-9123-87dd3c187239.png)
FPC:
![crew-fpc](https://user-images.githubusercontent.com/156656/93513018-7fb69600-f925-11ea-8d9e-d5e01ea852c3.png)

Reason is probably the original was `320x200`, which was double-scaled to `640x400` in FPC-SDL port, and 40-pixel black bars added at top and bottom to make it fit in standard `640x480` window. in Python, probably the easiest way is to just make a window `640x400` instead of `640x480` and it should fix itself.

**Comment by nukebloodaxe** [comment]
It is indeed a factor of the resizing, although this is dynamic.  If you look carefully at global_constants.py, there is the following line:
size = width, height = 640, 480  # screen dimensions
This is intended to be adjustable later, but if you change the numbers, it should scale for many areas (untested.)

Resizing is a bit brute-force right now, just to get things going :)

**Comment by mnalis** [comment]
Yes, it seems to resize correctly when I change it there, but then I can't progress after main menu (to begin new game and choose ship / crew etc.) - *anywhere* I click is interpreted as if I selected "Introduction" main menu item. (See https://github.com/nukebloodaxe/Ironseed-py/issues/6)

**Comment by nukebloodaxe** [comment]
#6 should now be closed, welcome to Alpha :)  The button resizing code has now been added to a few more areas.  Font resizing is on the cards, so text won't display correctly for resolutions below 640x480 yet.

**Comment by mnalis** [comment]
yup, game can now be started and pictures are not distorted when I change to `size = width, height = 640, 400`

**Comment by nukebloodaxe** [comment]
This issue is currently closed, resizing is much better than before, and the button code is "sensible" enough to address the problems that resolution changes bring to positioning.
