### ISSUE TITLE
Numbers reported by probes should be rounded

### ISSUE THREAD

**Issue by mnalis** [nukebloodaxe/Ironseed-py#5]
**Describe the bug**
Numbers reported by probes should be rounded on smaller number of decimal places

**To Reproduce**
Please describe the steps to reproduce the behaviour:
1. Start new game
2. Click on "land", "sea", "air", "life", "anom" and wait for probes to return after each one
3. Observe results like "Atmosferic pressure: 4.1999999999999999999 Atm"

**Expected behaviour**
It should probable be more like "Atmosferic pressure: 4.19 Atm" or "4.2 Atm" or whatever precision is reasonable

**Screenshots**
![probe-numbers](https://user-images.githubusercontent.com/156656/95622842-92c80c00-0a74-11eb-9af8-bb3fcf362f01.png)

**Comment by nukebloodaxe** [comment]
With this one, cosmetic change after getting the pie-graph and legend information working.  It's simple to do, just matter of getting to it.

**Comment by nukebloodaxe** [comment]
Addressed in commit [010213023dc5a175851e6958feb646d1398070c2](https://github.com/nukebloodaxe/Ironseed-py/commit/010213023dc5a175851e6958feb646d1398070c2)
Numbers are now rounded.
