### ISSUE TITLE
Allow to skip introduction

### ISSUE THREAD

**Issue by mnalis** [nukebloodaxe/Ironseed-py#6]
**Is your feature request related to a problem? Please describe.**
When game is started via `game.main_loop()`, introduction is run firstly... On slower computers it especially takes a long time, and after seeing it a few times, players/testers may not want to watch intro again.

Luckily, when a key is pressed while intro is running, introduction is interrupted and main loader screen with "Begin new game" / "Continue game" / "Introduction" / "Quit game" is shown.

Unluckily, when "Begin new game" is selected, the introduction will run again if it was interrupted before.

**Describe the solution you'd like**.
Intro should NOT be run again when any option other than "Introduction" is selected.

**Comment by mnalis** [comment]
Ah, it actually works in original game, but when screen height is changed as suggested in https://github.com/nukebloodaxe/Ironseed-py/issues/2, then this bug manifests - it seems that if screen is not 640x480 (but 640x400 for example), clicking *anywhere* on the screen acts as "Introduction" was selected every time.

When I restore resolution to 640x480, I can normally select "Begin new game" or other options

**Comment by nukebloodaxe** [comment]
I definitely have this one on the todo list :)  It's one of those where the location handling logic needs to be made more resolution agnostic, then it'll behave.  I've recently fixed the merging text in the intro to behave itself in a better variety of resolutions, for example.

**Comment by nukebloodaxe** [comment]
Closed via merge 165b2eb , made buttons resolution agnostic in areas which did not yet have new button resolution resizing logic.
